### ISSUE TITLE
add logo

### ISSUE THREAD

**Issue by louislarry** [panaceaid/panaceaid.github.io#2]

**Comment by louislarry** [comment]
use fiverr or sribu

**Comment by Gege24** [comment]
![Uploading Panacea Logo.png…]()

**Comment by Gege24** [comment]
![panacea logo](https://cloud.githubusercontent.com/assets/17737615/13627034/d36f866a-e5f9-11e5-8e4b-873caa9fb31b.png)

Panacea Logo; 
Logo as in pic no.1 (with the same P letter)
Wing as pic no.2
Snake as in pic no.3
Final Result like pic No.4

**Comment by Gege24** [comment]
![panacea 2](https://cloud.githubusercontent.com/assets/17737615/13627200/5101d190-e5fb-11e5-913e-852b788cc6a3.jpg)

Dibuat Flat Design kekira seperti ini

**Comment by darkbcx** [comment]
![panacea_logo_1](https://cloud.githubusercontent.com/assets/1042087/13910442/c796c844-ef54-11e5-8e04-1d233f7dee79.png)
![panacea_logo_2](https://cloud.githubusercontent.com/assets/1042087/13910443/c798ea66-ef54-11e5-9d71-b3231e8735ba.png)
![panacea_logo_3](https://cloud.githubusercontent.com/assets/1042087/13910444/c79b3aa0-ef54-11e5-81fa-6966c5bf0d41.png)
